_BASE_: "./Base.yaml"

# 这边还得配置一下，在 adet/data/builtin.py
DATASETS:
  TRAIN: ("xunfei_para_train",)
  TEST: ("xunfei_para_test",)  

MODEL:
  WEIGHTS: "output/pretrain/totaltext_ctw_r50.pth"  # or the provided pre-trained model

SOLVER:
  IMS_PER_BATCH: 2
  BASE_LR: 5e-5
  LR_BACKBONE: 5e-6
  WARMUP_ITERS: 0
  STEPS: (160000,) # (8000,) # (16000,) # 学习率调整iter
  MAX_ITER: 200000 # 20000
  CHECKPOINT_PERIOD: 40000 # 4000 # 20000

TEST:
  EVAL_PERIOD: 2000

OUTPUT_DIR: "output/para_detr_r50"